# Generated by Django 4.1.5 on 2023-10-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('form_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_code', to='index.form')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
