# Generated by Django 4.1.5 on 2023-10-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_form_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
