# Generated by Django 4.1.5 on 2023-10-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_form_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadBanner',
        ),
    ]
