# Generated by Django 4.1.5 on 2023-03-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_form_background_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('simple_representative', 'Can view form responses'), ('event_organizer', 'Can view, edit, delete form'))},
        ),
    ]
