# Generated by Django 4.1.5 on 2023-03-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_mark_returned', 'Set book as returned'), ('simple_representative', 'Can view form responses'), ('event_organizer', 'Can view, edit, delete form'))},
        ),
    ]
