# Generated by Django 4.0.2 on 2023-03-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('simple_representative', 'Can view form responses'), ('event_organizer', 'Can view, edit, delete form')]},
        ),
    ]
