# Generated by Django 4.1.5 on 2023-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
